const colors = {
  default: {
    transparent: "transparent",
    vdscEleeva3Color: "#373435",
    vdscEleeva2Color: "#848688",
    vdscEleeva1Color: "#199ac5",
    vdscBackground3Color: "#e6eff9",
    vdscBackground2Color: "#f1f3f8",
    vdscBackground1Color: "#fafafc",
    vdscLightLowColor: "#f2f2f5",
    vdscLightMediumColor: "#999988",
    vdscLightHighColor: "#ebebf0",
    vdscDarkLowColor: "#8f90a6",
    vdscDarkLow: "#313138",
    vdscDarkMedium: "#555770",
    vdscDarkMediumColor: "#0c0c10",
    vdscDarkHighColor: "#131317",
    vdscDarkHoverColor: "#31313805",
    vdscDarkHoverColorBorder: "#36363657",
    vdscAuxiliaryBlueLowColor: "#9dbff9",
    vdscAuxiliaryBlueMediumColor: "#5b8def",
    vdscAuxiliaryBlueHighColor: "#0063f7",
    vdscAuxiliaryBlue400: "#3E7BFA",
    vdscAuxiliaryBlue100: "#ccddff",
    vdscAuxiliaryDisabledLowColor: "#9fa8b2",
    vdscAuxiliaryWhiteLowColor: "#fefefe",    
    vdscAuxiliaryGrayLowColor: "#F3F3F3",
  },
  primary: {
    white: "#ffffff",
    black: "#000000",
  },
  badge: {
    vdscBadgeInformation: "#0063F7",
    vdscBadgeInformationAlternative1: "#e5f0ff",
    vdscBadgeCritical: "#e73b3b",
    vdscBadgeCriticalAlternative1: "#ffe6e6",
    vdscBadgeWarning: "#ff8800",
    vdscBadgeWarningAlternative1: "#FFF8E6",
    vdscBadgeSuccess: "#05a660",
    vdscBadgeSuccessAlternative1: "#E3FFF1",
    vdscBadgeIndeterminate: "#8F90A6",
    vdscBadgeIndeterminateAlternative1: "#ffffff",
    vdscBadgeIndeterminateAlternative2: "#e4e4eb",
    vdscBadgeIndeterminateAlternative3: "#28293D",
    vdscBadgeNormal: "#3E7BFA",
    vdscBadgeNormalAlternative1: "#FAFAFC",
    vdscBadgeMinor: "#e5b800",
    vdscBadgeMinorAlternative1: "#fffee6",
  },
};

export default colors;
