const colors = {
    default: {
        vdscEleeva3Color: "#373435",
        vdscEleeva2Color: "#848688",
        vdscEleeva1Color: "#199ac5",
        vdscBackground3Color: "#e6eff9",
        vdscBackground2Color: "#f1f3f8",
        vdscBackground1Color: "#fafafc",
        vdscLightLowColor: "#f2f2f5",
        vdscLightMediumColor: "#999988",
        vdscLightHighColor: "#ebebf0",
        //vdscDarkLowColor: "#8f90a6",
        vdscDarkLowColor: "#313138",
        //vdscDarkMediumColor: "#555770",
        vdscDarkMediumColor: "#0c0c10",
        //vdscDarkHighColor: "#1C1C28",
        vdscDarkHighColor: "#131317",
        vdscDarkHoverColor: "#31313805",
        vdscAuxiliaryBlueLowColor: "#9dbff9",
        vdscAuxiliaryBlueMediumColor: "#5b8def",
        vdscAuxiliaryBlueHighColor: "#0063f7",
        vdscAuxiliaryBlue400: "#3E7BFA",
        vdscAuxiliaryBlue100: "#ccddff",
        vdscAuxiliaryCyanLowColor: "#a9eff2",
        vdscAuxiliaryCyanMediumColor: "#73dfe7",
        vdscAuxiliaryCyanHighColor: "#00cfde",
        vdscAuxiliaryWhiteLowColor: "#fefefe",
        vdscAuxiliaryDisabledLowColor: "#9fa8b2",
        vdscAuxiliaryPurpleLowColor: "#dda5e9",
        vdscAuxiliaryPurpleMediumColor: "#ac5dd9",
        vdscAuxiliaryPurpleHighColor: "#6600cc",
        vdscAuxiliaryOrangeLowColor: "#fccc75",
        vdscAuxiliaryOrangeMediumColor: "#fdac42",
        vdscAuxiliaryOrangeHighColor: "#ff8800",
        vdscAuxiliaryYellowLowColor: "#ffff8d",
        vdscAuxiliaryYellowMediumColor: "#ffea00",
        vdscAuxiliaryYellowHighColor: "#ffd600",
        vdscAuxiliaryRedLowColor: "#ff8080",
        vdscAuxiliaryRedMediumColor: "#ff5c5c",
        vdscAuxiliaryRedHighColor: "#ff3b3b",
        vdscAuxiliaryGreenLowColor: "#57eba1",
        vdscAuxiliaryGreenMediumColor: "#39d98a",
        vdscAuxiliaryGreenHighColor: "#06c270",
        vdscAuxiliaryGrayLowColor: "#F3F3F3",
    },
    primary: {
        white: "#ffffff",
        black: "#000000",
    },
    stateDefault: {
        vdscStateUnknownDefault: "#555770",
        vdscStateNoDataDefault: "#8F90A6",
        vdscStateInactiveDefault: "#0063F7",
        vdscStateAvailableDefault: "#06C270",
        vdscStateUnavailableDefault: "#FF5C5C",
        vdscStateMaintenanceDefault: "#FF8800",
    },
    stateAlternative: {
        vdscStateUnknownAlternative1: "#555770",
        vdscStateNoDataAlternative1: "#8F90A6",
        vdscStateInactiveAlternative1: "#5C769E",
        vdscStateAvailableAlternative1: "#4CD1FF",
        vdscStateUnavailableAlternative1: "#FF0000",
        vdscStateMaintenanceAlternative1: "#FF9B00",
    },
    severityDefault: {
        vdscSeveritySecurityDefault: "#28293D",
        vdscSeverityCriticalDefault: "#FF3B3B",
        vdscSeverityMajorDefault: "#FF8800",
        vdscSeverityMinorDefault: "#FFC745",
        vdscSeverityWarningDefault: "#FF5C5C",
        vdscSeverityDebugDefault: "#6600CC",
        vdscSeverityTraceDefault: "#9FA8B2",
        vdscSeverityIndeterminateDefault: "#9FA8B2",
        vdscSeverityUnknowDefault: "#9FA8B2",
        vdscSeverityNormalDefault: "#0CAB66",
        vdscSeverityClearedDefault: "#0CAB66",
        vdscSeverityOkDefault: "#0CAB66",
        vdscSeverityInformationalDefault: "#0CAB66",
    },
    severityAlternative: {
        vdscSeveritySecurityAlternative1: "#151516",
        vdscSeverityCriticalAlternative1: "#FF0000",
        vdscSeverityMajorAlternative1: "#FF9B00",
        vdscSeverityMinorAlternative1: "#FFD36D",
        vdscSeverityWarningAlternative1: "#FF5C5C",
        vdscSeverityDebugAlternative1: "#555770",
        vdscSeverityTraceAlternative1: "#8F90A6",
        vdscSeverityIndeterminateAlternative1: "#8F90A6",
        vdscSeverityUnknowAlternative1: "#8F90A6",
        vdscSeverityNormalAlternative1: "#4CD1FF",
        vdscSeverityClearedAlternative1: "#4CD1FF",
        vdscSeverityOkAlternative1: "#4CD1FF",
        vdscSeverityInformationalAlternative1: "#4CD1FF",
    }
};

export default colors;
